name: "Push"

on:
  push:
    branches:
      - main
  schedule:
    -   cron: "0 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Push
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup dependencies
        run: yarn

      - name: Run push.sh
        run: ./push.sh
        env:
          MONGO_DB: ${{ secrets.MONGO_DB }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_DB_PROD: ${{ secrets.PG_DB_PROD }}