name: "Push"

on:
  push:
    branches:
      - main
  schedule:
    -   cron: "0/30 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Push
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup dependencies
        run: yarn

      - name: Run push.sh
        run: ./push.sh